title: Ryought::Lab
author: Ryo Nakabayashi
email: ryonakabayashi@gmail.com
description: >-
  Ryo Nakabayashi (ryought) Bioinformatics and web engineer
baseurl: ""
url: "https://ryought.app"

# Build settings
markdown: kramdown
kramdown:
  input: GFM
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap

sitemap:
  file: "/sitemap.xml"
  # include_posts:
    # - index.html
    # - about.html
    # - projects.html

# minima-specific settings
# https://github.com/jekyll/minima/tree/v2.5.0
show_excerpts: true
twitter_username: ryought
github_username:  ryought
facebook_username: ryo.nakabayashi
rss: rss
header_pages:
  - about.md
  - projects.html
minima:
  date_format: "%Y-%m-%d"
  disqus:
    shortname: "ryought-lab"

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
