title: Ryought::Lab
title_separator: "|"
email: ryonakabayashi@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Ryo Nakabayashi(ryought) Bioinformatics and Web Engineer
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ryought.app" # the base hostname & protocol for your site, e.g. http://example.com

author:
  name: "Ryo Nakabayashi"
  avatar: "assets/ryought.jpg"
  bio: "UTokyo BioInfo B4"
  location: "Tokyo, Japan"
  email: "nakabayashi@gmail.com"
  github: "ryought"
  twitter: "ryought"

# 投稿のコメント欄 disqusを使う
comments:
  provider: "disqus"
  disqus:
    shortname: "ryought-lab"

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  footnote_nr: 1

plugins:
  - jekyll-sitemap
  - jemoji

sitemap:
  file: "/sitemap.xml"
  include_posts:
    - index.html
    - details.html
    - projects.html

include:
  - .htaccess
  - _pages/
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - old/  # old ryought::lab website sources
  - README.md
  - Makefile
encoding: "utf-8"
